# Generated by Django 4.1.5 on 2023-02-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillsAndSales', '0003_cart_area_cart_house_cart_landmark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
