# Generated by Django 4.1.5 on 2023-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillsAndSales', '0004_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
