# Generated by Django 4.1.5 on 2023-02-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillsAndSales', '0005_cart_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('toatalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='billcalculations',
            name='BillId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billcalculations',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
