# Generated by Django 4.1.5 on 2023-02-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillsAndSales', '0007_remove_billcalculations_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billfinal',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
