# Generated by Django 4.1.5 on 2023-02-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_category',
            field=models.CharField(choices=[('measuring tools', 'measuring tools'), ('Striking tools', 'Striking tools'), ('Metal cutting tools', 'Metal cutting tools'), ('Holding tools', 'Holding tools'), ('Sharpening tools', 'Sharpening tools'), ('grinding tools', 'grinding tools'), ('Other', 'Other')], max_length=255),
        ),
    ]
